### ISSUE TITLE
DnD only working on Chrome

### ISSUE THREAD

**Issue by Teqa** [surveyjs/editor#1]
The visual editor has a nice DnD for ordering questions. 
This works on Chrome, but Firefox is not working
Tested on Developer edition 45 and normal FF 45
MS Edge is also working.

**Comment by andrewtelnov** [comment]
There is a bug in FF: https://bugzilla.mozilla.org/show_bug.cgi?id=646823
I was using <button> tag for rendering question elements.
I'm using <div> tag now. Additionally, there was a bug of obtaining dataTransfer. It is fixed as well.

Thank you,
Andrew Telnov-

**Comment by joshreid** [comment]
Hi Andrew

This looks like an issue still/again (??) 
Can replicate on [http://editor.surveyjs.io/examples/options.html]
Firefox PC/Mac 52.0.1

Can drag toolbox item, but when it's dropped the page navigates to empty url.

![screen shot 2017-05-11 at 3 21 46 pm](https://cloud.githubusercontent.com/assets/167671/25931003/985403e8-365d-11e7-8143-9cb5408ed750.png)


Maybe it should be a new issue?

**Comment by andrewtelnov** [comment]
@joshreid Yes, I was able to reproduce it. on my version of FF.

**Comment by tsv2013** [comment]
@joshreid We've fixed it with the 709e481f65280921978f3b8d58f54851cd6ee9b6 commit. We will release an update today.

**Comment by joshreid** [comment]
Thanks Andrew - As always stella work.

**Comment by tsv2013** [comment]
0.12.14 has been released
